version: '3.7'

services:
  reverse-proxy:
    container_name: reverse-proxy
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - api-network

  user-api-service:
    build: ../usermicroservice
    depends_on:
      - user-database-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-database-service:5432/user-database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    ports:
      - "5004:5004"
    networks:
      - user-network
      - api-network

  user-database-service:
    image: 'postgres:13.2-alpine'
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=user-database
    ports:
      - "6004:5432"
    networks:
      - user-network

networks:
  user-network:
    driver: bridge
  api-network:
    driver: bridge